hash-format = "sha256"

[[files]]
file = "config/appleskin.json5"

[[files]]
file = "config/customwindowtitle-client.toml"

[[files]]
file = "config/customwindowtitle/icon.png"

[[files]]
file = "config/default-hotkeys.json"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/inline_tooltips.toml"

[[files]]
file = "config/isxander-main-menu-credits.json"

[[files]]
file = "config/item_descriptions.toml"

[[files]]
file = "config/modernfix-mixins.properties"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/styledplayerlist/config.json"

[[files]]
file = "config/styledplayerlist/styles/default.json"

[[files]]
file = "config/themetip.toml"

[[files]]
file = "config/waila/blacklist.json5"

[[files]]
file = "config/waila/waila.json5"

[[files]]
file = "config/waila/waila_plugins.json5"

[[files]]
file = "mods/Apoli-2.12.0-alpha.17+mc.1.21.1-blanketcon6.jar"

[[files]]
file = "mods/Origins-1.13.0-alpha.12-waterless+mc.1.21.1.jar"

[[files]]
file = "mods/altorigingui.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/apathy.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/badstdout.pw.toml"
metafile = true

[[files]]
file = "mods/better-log4j-config.pw.toml"
metafile = true

[[files]]
file = "mods/boring-default-game-rules.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/custom-window-title.pw.toml"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
metafile = true

[[files]]
file = "mods/dontdothat.pw.toml"
metafile = true

[[files]]
file = "mods/drogstyle.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-brightness.pw.toml"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/euphonium.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
metafile = true

[[files]]
file = "mods/fabrictailor-2.5.0+bc25.1.jar"

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/hoofprint.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/inline_tooltips-1.6.3-alt+1.21.1-fabric.jar"

[[files]]
file = "mods/inventory-tabs.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/loadingscreentips.pw.toml"
metafile = true

[[files]]
file = "mods/mcqoy.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/music-moods.pw.toml"
metafile = true

[[files]]
file = "mods/origins-minus.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/picohud.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/portable-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-snowy-fix-(forge-fabric).pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sseds.pw.toml"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/swingthrough.pw.toml"
metafile = true

[[files]]
file = "mods/switchy.pw.toml"
metafile = true

[[files]]
file = "mods/themetip-u0.6-kaleido.jar"

[[files]]
file = "mods/tinkerers-smithing.pw.toml"
metafile = true

[[files]]
file = "mods/tinkerers-statures.pw.toml"
metafile = true

[[files]]
file = "mods/totem-anywhere.pw.toml"
metafile = true

[[files]]
file = "mods/trimmable-tools.pw.toml"
metafile = true

[[files]]
file = "mods/vehiclefix.pw.toml"
metafile = true

[[files]]
file = "mods/village-healthcare.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "resourcepacks/compact-font.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/unsanded.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/Unsanded-1.1.1-custom.zip"

[[files]]
file = "resources/resourcepack/required/branding/assets/minecraft/texts/credits.json"

[[files]]
file = "resources/resourcepack/required/branding/assets/minecraft/texts/splashes.txt"

[[files]]
file = "resources/resourcepack/required/branding/assets/minecraft/textures/gui/title/edition.png"

[[files]]
file = "resources/resourcepack/required/branding/assets/minecraft/textures/gui/title/minecraft.png"

[[files]]
file = "resources/resourcepack/required/branding/assets/minecraft/textures/gui/title/mojangstudios.png"

[[files]]
file = "resources/resourcepack/required/branding/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/font/emoji.json"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/font/icons.json"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/ace_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/agender_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/aro_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/aroace_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/bi_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/demi_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/femboy_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/furry_pride.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/genderfluid_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/genderqueer_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/intersex_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/lesbian_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/nb_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/pan_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/plural_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/queer_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/assets/pride/textures/emoji/trans_heart.png"

[[files]]
file = "resources/resourcepack/required/pride_emoji/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/pride_emoji/styled_chat_emoji.json"

[[files]]
file = "resources/resourcepack/required/twemoji.zip"

[[files]]
file = "server-icon.png"

[[files]]
file = "server.properties"
