name = "Creature Comforts Neo"
author = "Sisby folk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.2.0"

[options]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
