[flavor_groups.modded]
name = "Modded Content"
side = "both"
description = "Whether to ship Creature Comforts with vanilla-incompatible content."
[[flavor_groups.modded.choices]]
id = "byo"
name = "BYO"
description = "No modded content added. Your worlds will remain compatible with vanilla - or add your own selection of content mods!"
[[flavor_groups.modded.choices]]
id = "chefs_choice"
name = "Chef's Choice"
description = "Include a small selection of cohesive, self-contained content mods. Installs Cerulean and Spectrum"

[metafile.ars-nouveau]
flavors="chefs_choice"

[metafile.create]
flavors="chefs_choice"

[metafile.curios]
flavors="chefs_choice"

[metafile.geckolib]
flavors="chefs_choice"

[metafile.lodestonelib]
flavors="chefs_choice"

[metafile.malum]
flavors="chefs_choice"

[metafile.modonomicon]
flavors="chefs_choice"

[metafile.paradise-lost]
flavors="chefs_choice"

[metafile.productivebees]
flavors="chefs_choice"

[metafile.quark]
flavors="chefs_choice"

[metafile.resourceful-lib]
flavors="chefs_choice"

[metafile.revelationary]
flavors="chefs_choice"

[metafile.spectrum]
flavors="chefs_choice"

[metafile.the-bumblezone]
flavors="chefs_choice"

[metafile.tropicraft]
flavors="chefs_choice"

[metafile.zeta]
flavors="chefs_choice"
