# Enable tooltip border gradient.
# default: true
gradient = true
# Enables the extra pixel on the outside of the border.
# default: true
thickEdges = true
# The primary color of the border gradient
# #AARRGGBB, in hex
# matches r'#[0-9A-Fa-f]{8}'
# default: #505000FF
primaryColor = "#906BC39F"
# The secondary color of the border gradient
# #AARRGGBB, in hex
# matches r'#[0-9A-Fa-f]{8}'
# default: #5028007F
secondaryColor = "#904E7EDA"
# The color of the tooltip background
# #AARRGGBB, in hex
# matches r'#[0-9A-Fa-f]{8}'
# default: #F0100010
backgroundColor = "#F01F153A"
# Lets Marie know that you are really awesome!
# default: true
importantSetting = true
