name: Build & Deploy Modpack

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["1.21", "1.21-neo"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  PACKWIZ_COMMIT: 52b123018f9e19b49703f76e78ad415642acf5c5
  PACKWIZ_DIR: /tmp/packwiz_artifact
  PACKWIZ: /tmp/packwiz_artifact/packwiz

jobs:
  deploy_packwiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: "1.21"

      - name: Checkout neo
        uses: actions/checkout@v4
        with:
          ref: "1.21-neo"
          path: neo
          clean: false

      # Set up dependencies

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install main python dependencies
        run: pip install -r requirements.txt

      - name: Download Packwiz
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: packwiz/packwiz
          workflow: go.yml
          name: "Linux 64-bit x86"
          path: ${{ env.PACKWIZ_DIR }}
          branch: "main"
      - name: Make packwiz executable
        run: chmod +x ${{ env.PACKWIZ }}

      # Build

      - name: Build main pack
        run: python scripts/assemble_packwiz.py

      - name: Build neo pack
        run: python neo/scripts/assemble_packwiz.py

      # Setup test-runner cache
      - name: Generate cache key
        run: python scripts/run_test.py
        env:
          GENERATE_DESIRED_CACHE_STATE_AND_EXIT: true
      - name: Cache test-runner (static cache)
        uses: actions/cache@v4
        with:
          path: run/cache-static/
          key: test-run-static-cache-${{ hashFiles('run/desired_cache_state_for_static_cache.json') }} # Try and get the desired state
          restore-keys: test-run-static-cache- # But fall back if needed
      - name: Cache test-runner (dynamic cache)
        uses: actions/cache@v4
        with:
          path: run/cache-dynamic/
          key: test-run-dynamic-cache-${{ hashFiles('generated/pack/pack.toml') }} # pack.toml contains hashes for all other files
          restore-keys: test-run-dynamic-cache-

      # Run tests
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Test main pack
        run: python scripts/run_test.py

      - name: Test neo pack
        run: python neo/scripts/run_test.py

      - name: Build unsup
        run: python scripts/assemble_unsup.py

      - name: Build unsup
        run: python neo/scripts/assemble_unsup.py

      - name: Copy neo pack
        run: cp -r neo/generated/pack generated/pack/neo

      - name: Copy neo unsup packs
        run: cp -n neo/generated/* generated/pack

      - uses: actions/upload-artifact@v4
        with:
          path: generated/*.zip

      - name: Configure pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: generated/pack/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
